name: Database Deployment

on:
  workflow_dispatch:
  
jobs:
  build :
    runs-on: windows-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup MSBuild
       uses: microsoft/setup-msbuild@v1.3.1

     - name: Build DACPAC
       run: msbuild 'SQLDataBaseProject.sln' /p:TargetFrameworkVersion=v4.7.2 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider

     - name: Upload artifact
       uses: actions/upload-artifact@v3.1.2
       with:
          name:  SQLDB
          path: ${{ github.workspace }}/SQLDataBaseProject/bin/debug/ 

          
  deploy: 
    needs: build
    environment: DEV
    runs-on: windows-latest

    steps:
               
      - name: download artifact containing dacpac
        uses: actions/download-artifact@v3.0.2
        with:
          name: SQLDB

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.2.1
        with:
          connection-string: '${{ secrets.CONNECTION_STRING }}'
          path: './SQLDataBaseProject.dacpac'
          action: publish
          arguments: '/p:DropObjectsNotInSource=true'
