name: Validacion Sandbox

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
    - SQLDataBaseProject/**
jobs:
  build :
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build DACPAC
        run: msbuild 'SQLDataBaseProject/SQLDataBaseProject.sqlproj /p:TargetFrameworkVersion=v4.7.2 /p:DSP=Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider
